Create vote execute chores create commune
redhat-beyond/commune pull request #102
Opened 2023-01-21 19:42 UTC by RonTuretzky

2023-01-21 20:43 UTC, ofirtzabari submitted a review, later dismissed

2023-01-21 20:43 UTC, EliasAndry approved these changes, later dismissed
perfeecttttt

2023-01-21 21:06 UTC, kobihk requested changes

2023-01-21 21:06 UTC, kobihk commented on commune_app/all_models/votes.py
> +        Vote.create_new_vote(voting_user=self.id, voted_chore=chore_id, vote_bool=decision)
This is the same method as "create_new_vote" with a different name "vote"
Do we need it? 
```suggestion
```

2023-01-21 21:06 UTC, kobihk commented on commune_app/views.py
> +        return redirect('commune')
if the return is the same for all options so you can do it once.
like:
```suggestion
    return redirect('commune')
```

2023-01-22 05:29 UTC, kobihk approved these changes, later dismissed

2023-01-22 05:38 UTC, kobihk approved these changes

2023-01-22 05:39 UTC, merged