adding contributing guide and project description
redhat-beyond/commune pull request #11
Opened 2022-11-10 07:31 UTC by RonTuretzky

Unsure whether the description is meaningful enough 

For the contribution guidelines, we haven't really created clear norms so I put some baseline instructions for now

Would appreciate the input!

2022-11-10 07:33 UTC, RonTuretzky commented
Also, I understand an Architecture guide is required, and a user guide is optional, are these things that are in the scope of our demo for next week?

2022-11-10 10:37 UTC, NicolePauzner requested changes
Git commit message should start with a capital letter and be in imperative mood and not in indicative mood i.e. change adding to Add

2022-11-10 11:49 UTC, kobihk requested changes

2022-11-10 11:49 UTC, kobihk commented on CONTRIBUTING.md
> +Development process
Please take a look at the previous contributing guides for inspiration:
https://github.com/redhat-beyond/AcadeMe/blob/main/contributing.md
https://github.com/redhat-beyond/Xpense/blob/main/CONTRIBUTING.md

2022-11-10 15:42 UTC, NicolePauzner submitted a review, later dismissed

2022-11-10 16:51 UTC, EliasAndry submitted a review, later dismissed

2022-11-11 11:43 UTC, FaezZangariya submitted a review, later dismissed

2022-11-11 13:16 UTC, EliasAndry approved these changes

2022-11-11 13:22 UTC, NicolePauzner approved these changes

2022-11-12 16:24 UTC, kobihk approved these changes

2022-11-12 16:24 UTC, merged