Adding Expense model
redhat-beyond/commune pull request #29
Opened 2022-11-27 11:05 UTC by FaezZangariya

added Expense model and related migration

2022-12-01 09:14 UTC, bennypowers requested changes
small changes otherwise lgtm

2022-12-01 09:14 UTC, bennypowers commented on .flake8
> +    commune_app/migrations/0001_initial.py: E501
can make this a glob to ignore all generated files

2022-12-01 09:14 UTC, bennypowers commented on commune_app/models.py
> +class User(AbstractUser):
we'd prefer to have docstrings on all classes

2022-12-01 10:41 UTC, kobihk requested changes
@FaezZangariya this is the first PR I can see tests. 
great!!!
There is a code that is relevant to the user PR but I ignored it

2022-12-01 10:41 UTC, kobihk commented on commune_app/tests/test_Expense_model.py
> +        assert expense.budget == "150"
I think it should be a number(int) not a string
```suggestion
        assert expense.budget == 150
```

2022-12-01 10:41 UTC, kobihk commented on commune_app/tests/test_Expense_model.py
> +    def test_get_expense_by_title(self):
same as above 
you could use the same user you already created as a fixture like:
```suggestion
    def test_get_expense_by_title(self, user1):
```

2022-12-01 10:41 UTC, kobihk commented on commune_app/tests/test_Expense_model.py
> +        expense3 = Expense.create_expense(title="Z", budget="300", date="2011-09-01T13:20:30+03:00", assign=currU)
you can do the same as I suggested with user1 regarding the expenses to do them as a fixture and reuse them

2022-12-01 17:52 UTC, RonTuretzky requested changes

2022-12-01 17:52 UTC, RonTuretzky commented on commune_app/models.py
> +class Expense(models.Model):
```suggestion
class Expense(models.Model):
    id = models.IntegerField(unique=True, primary_key=True)
```
adding id so you can use it for the getter later

2022-12-01 17:52 UTC, RonTuretzky commented on commune_app/models.py
> +    def get_expense_by_title(title):
```suggestion
    def get_expense_by_pk(pk):
```

2022-12-01 17:52 UTC, RonTuretzky commented on commune_app/models.py
> +            expense = Expense.objects.filter(title=title).order_by('date').first()
```suggestion
            expense = Expense.objects.filter(id=id)
```

2022-12-10 15:27 UTC, ofirtzabari approved these changes
Look good

2022-12-27 03:17 UTC, closed without merging

2022-12-27 03:18 UTC, FaezZangariya commented
We decided that the Expense model is not really needed