Erd dfd
redhat-beyond/commune pull request #33
Opened 2022-11-27 15:41 UTC by RonTuretzky

#32

2022-11-27 16:23 UTC, ofirtzabari approved these changes
good job

2022-11-27 17:11 UTC, kobihk requested changes
- Please update the PR title to be more informative
- There is the same user for all?! which means I can join the commune and delete everyone :)  or change the expenses... IMHO you should add a manager that has extra privilege

2022-11-29 08:01 UTC, EliasAndry approved these changes

2022-11-29 13:40 UTC, EliasAndry approved these changes

2022-12-01 14:52 UTC, RonTuretzky commented on CONTRIBUTING.md
> +![DFD](https://user-images.githubusercontent.com/74178515/204143717-32b0ef58-5bdd-438f-9523-9184e3921f9e.png)
PR title amended 
There is a user table, the commune model holds a collection of users who are members, they can only suggest decisions
Adding a manager with elevated priviliges kind of defeats the purpose imo 
Moving to the read me @kobihk

2022-12-01 14:56 UTC, FaezZangariya approved these changes

2022-12-01 16:40 UTC, kobihk approved these changes

2022-12-01 19:51 UTC, EliasAndry approved these changes

2022-12-02 18:47 UTC, ofirtzabari approved these changes
LGTM

2022-12-02 18:47 UTC, ofirtzabari commented
LGTM

2022-12-03 21:50 UTC, merged