Add pytest
redhat-beyond/commune pull request #34
Opened 2022-11-27 16:18 UTC by ofirtzabari

Install pytest-django
check the pytest work
close #30

2022-11-27 17:22 UTC, kobihk requested changes

2022-11-27 17:22 UTC, kobihk commented on Pipfile
> +pytest-django = "*"
what about pytest package?
how do you make it trigger for each PR? 
where is the test for example?
please look at my comment in:
https://github.com/redhat-beyond/commune/pull/31

2022-11-28 19:58 UTC, kobihk approved these changes

2022-11-29 08:01 UTC, EliasAndry approved these changes

2022-11-29 13:07 UTC, FaezZangariya approved these changes

2022-11-29 13:39 UTC, EliasAndry approved these changes

2022-11-29 14:24 UTC, merged