Commune model
redhat-beyond/commune pull request #35
Opened 2022-11-27 17:59 UTC by RonTuretzky

#24

2022-11-29 13:10 UTC, FaezZangariya approved these changes
just fix the flake8 errors , other than that looks good to me for now

2022-12-01 09:16 UTC, bennypowers approved these changes

2022-12-01 09:16 UTC, bennypowers commented on commune_app/models.py
> +class Commune(Models.Model):
we'd prefer to have docstrings on all classes

2022-12-27 14:15 UTC, kobihk requested changes

2022-12-27 14:15 UTC, kobihk commented on commune_app/models.py
> +class User(AbstractUser):
This code already merged as part of:
https://github.com/redhat-beyond/commune/pull/27

please rebase

2022-12-27 14:15 UTC, kobihk commented on CONTRIBUTING.md
> +
It is already part of:
https://github.com/redhat-beyond/commune/blob/main/README.md 
Please remove it

2023-01-02 22:00 UTC, kobihk commented on CONTRIBUTING.md
> +
@RonTuretzky please reply to the comments and rebase

2023-01-04 12:57 UTC, closed without merging