Auto add users
redhat-beyond/commune pull request #52
Opened 2023-01-02 06:17 UTC by ofirtzabari

create migrations file that auto add users when the app start to run close issue #51

2023-01-02 07:26 UTC, bennypowers submitted a review, later dismissed

2023-01-02 09:08 UTC, kobihk requested changes

2023-01-02 09:08 UTC, kobihk commented on commune_app/migrations/0002_add_user_test_data.py
> +            ('testUser123', 'testUser1@mta.ac.il', 'PasswordU$er123', '123'),
Please change it like this: 
```suggestion
            ('testUser123', 'testUser1@telhai.ac.il', 'PasswordU$er123', '123'),
```

2023-01-02 09:08 UTC, kobihk commented on commune_app/migrations/0002_add_user_test_data.py
> +            ('testUser345', 'testUser3@mta.ac.il', 'PasswordU$er789', '345')
same ^^

2023-01-02 09:08 UTC, kobihk commented on commune_app/migrations/0002_add_user_test_data.py
> +                user.set_password(user_password)
Please check if this line is necessary because in the above line the user initiated with the same password
```suggestion
```

2023-01-02 09:11 UTC, kobihk commented
> create migrations file that auto add users when the app start to run close issue #51

please update the description of this PR to something like this:
create a migrations file that auto add users when the app starts to run. 
fixed issue #51

2023-01-02 21:51 UTC, kobihk requested changes
@ofirtzabari please rebase

2023-01-03 08:48 UTC, ofirtzabari commented
> @ofirtzabari please rebase

done

2023-01-03 13:23 UTC, RonTuretzky reviewed
LGTM

2023-01-03 13:24 UTC, RonTuretzky approved these changes

2023-01-03 13:32 UTC, NicolePauzner approved these changes

2023-01-03 13:45 UTC, merged