Adding a Vagrantfile for spinning up a development VM
redhat-beyond/commune pull request #6
Opened 2022-11-09 14:17 UTC by ofirtzabari

Vagrant is a tool for using virtual machines to share development environments.
Learn more about it at:
https://www.vagrantup.com/

Also making changes to the `.gitignore` file to ignore any data that Vagrant
might create.

2022-11-09 14:55 UTC, kobihk requested changes
Please add in the description something like:
Fix issue #1

2022-11-09 14:55 UTC, kobihk commented on .gitignore
> +.vagrant
Please add a new line in the end of the file

2022-11-09 17:14 UTC, kobihk commented
@ofirtzabari Please add in the description of this PR something like:
`Fix issue #1`

2022-11-10 09:06 UTC, RonTuretzky requested changes
I think you need to do the steps that will allow local port forwarding so we can display it in our browser

2022-11-10 14:27 UTC, kobihk approved these changes
Please add in the description something like:
Fix issue #1

2022-11-10 16:50 UTC, EliasAndry submitted a review, later dismissed

2022-11-10 16:55 UTC, kobihk requested changes

2022-11-10 16:55 UTC, kobihk commented on Vagrantfile
> +  )
Please add indentation something like:
```suggestion
  config.vm.network(
	"forwarded_port", guest: 8000, host: 8000, host_ip: "127.0.0.1"
  )
```

2022-11-10 17:03 UTC, kobihk requested changes

2022-11-10 17:03 UTC, kobihk commented on Pipfile
> +[[source]]
IMHO the pipfiles should be part of PR #9

2022-11-10 22:12 UTC, kobihk commented
@ofirtzabari AFAICS you deleted all files
Please add back the Vagrantfile and the .gitignore files

2022-11-11 11:14 UTC, kobihk approved these changes

2022-11-11 11:15 UTC, merged