Adding Setup.sh and making changes to Vagrantfile
redhat-beyond/commune pull request #8
Opened 2022-11-09 21:23 UTC by FaezZangariya

Fix issue #3

2022-11-10 09:08 UTC, RonTuretzky reviewed
@ofirtzabari I think these are the changes that I was talking about in your PR 

@kobihk I think this needs to be merged after @ofirtzabari 's PR

2022-11-10 14:40 UTC, EliasAndry submitted a review, later dismissed

2022-11-10 16:57 UTC, kobihk requested changes

2022-11-10 16:57 UTC, kobihk commented on setup.sh
> +    python manage.py runserver 0.0.0.0:8000 > runserver.log 2>&1 &)
```suggestion
# run our app. Nohup and “&” are used to let the setup script finish
# while our app stays up. The app logs will be collected in nohup.out
nohup pipenv run python manage.py runserver 0.0.0.0:8000 &

```

2022-11-10 16:57 UTC, kobihk commented on Vagrantfile
> +# -*- mode: ruby -*-
After we will merge #6 you will need to rebase your PR 
Then this file probably will be redundant

2022-11-10 22:26 UTC, kobihk commented
@FaezZangariya please rename the file from setup.sh to bootstrap.sh
as you asked in the work division details:
`Student2: bootstrap.sh`

2022-11-11 11:19 UTC, kobihk commented
@FaezZangariya please update the title of this PR from:
"Adding Setup.sh and making changes to Vagrantfile"
to:
"Adding bootstrap.sh file"
and please ask for CR from your teammates.

2022-11-11 12:21 UTC, RonTuretzky approved these changes
LGTM!

2022-11-11 13:18 UTC, EliasAndry approved these changes

2022-11-12 16:15 UTC, kobihk approved these changes

2022-11-12 16:15 UTC, merged