Login
redhat-beyond/commune pull request #83
Opened 2023-01-14 12:19 UTC by RonTuretzky

#81

2023-01-14 20:50 UTC, FaezZangariya approved these changes

2023-01-15 08:35 UTC, kobihk approved these changes

2023-01-15 08:38 UTC, kobihk requested changes
This PR contains the same content as #84

2023-01-15 08:45 UTC, RonTuretzky commented
> This PR contains the same content as #84

84 is based on this PR but it also fixes a function in the views.py file which isn't addressed here

2023-01-15 14:09 UTC, kobihk approved these changes

2023-01-15 15:31 UTC, EliasAndry approved these changes

2023-01-15 16:19 UTC, merged