Login fix (WIP)
redhat-beyond/commune pull request #90
Opened 2023-01-17 15:56 UTC by RonTuretzky

2023-01-18 22:56 UTC, kobihk requested changes

2023-01-18 22:56 UTC, kobihk commented on commune_app/views.py
> +def user_login(request):
you have this line twice - here and in line # 43
please delete this line 
```suggestion
```

2023-01-19 14:22 UTC, EliasAndry approved these changes

2023-01-19 15:41 UTC, NicolePauzner approved these changes

2023-01-19 15:41 UTC, FaezZangariya submitted a review, later dismissed

2023-01-19 15:44 UTC, ofirtzabari submitted a review, later dismissed
amazing

2023-01-19 15:54 UTC, kobihk requested changes

2023-01-19 15:54 UTC, kobihk commented on commune_app/templates/base.html
> +
Please remove all the empty lines
```suggestion
```

2023-01-19 15:54 UTC, kobihk commented on commune_app/templates/commune_app/login.html
> +{% endblock %}
please add a new line

2023-01-19 15:54 UTC, kobihk commented on commune_app/templates/commune_app/logout.html
> +</html>
please add a new line

2023-01-19 15:54 UTC, kobihk commented on commune_app/templates/commune_app/logout.html
> +<!DOCTYPE html>
I think the logout should return to the main page 
IMHO we don't need this page

2023-01-19 15:59 UTC, kobihk requested changes

2023-01-19 15:59 UTC, kobihk commented on commune_app/templates/base.html
> +                    <li class="nav-item"><a href="{% url 'logout' %}" class="nav-link active text-white">Logout</a></li>
if the user is NOT authenticated 
I think you can remove this line - you don't need logout when the user is not logged in
```suggestion
```

2023-01-19 16:34 UTC, EliasAndry approved these changes
perfectooo

2023-01-19 16:38 UTC, FaezZangariya approved these changes

2023-01-19 16:39 UTC, kobihk approved these changes
Please open an issue to add tests for the pages in different PR

2023-01-19 16:40 UTC, merged