add chore test data
redhat-beyond/commune pull request #92
Opened 2023-01-19 17:09 UTC by ofirtzabari

Adding chore data
Arrangement of all the migrations files
fix #91

2023-01-19 17:22 UTC, FaezZangariya approved these changes
LGTM

2023-01-19 17:23 UTC, NicolePauzner approved these changes
LGTM

2023-01-19 17:38 UTC, kobihk requested changes

2023-01-19 17:38 UTC, kobihk commented on commune_app/migrations/0006_add_chore_test_data.py
> +            ('testChore5', 'discription 5', 500, True, True),
```suggestion
            ('testChore1', 'description 1', 100, False, False),
            ('testChore2', 'description 2', 200, False, False),
            ('testChore3', 'description 3', 300, True, False),
            ('testChore4', 'description 4', 400, True, False),
            ('testChore5', 'description 5', 500, True, True),
```

2023-01-19 17:42 UTC, RonTuretzky submitted a review, later dismissed

2023-01-19 18:52 UTC, FaezZangariya submitted a review, later dismissed

2023-01-20 14:30 UTC, kobihk approved these changes

2023-01-20 14:30 UTC, merged