adding jebtrains & ron's powershell script
redhat-beyond/commune pull request #99
Opened 2023-01-19 20:12 UTC by RonTuretzky

Fix #98

2023-01-19 23:16 UTC, kobihk requested changes

2023-01-19 23:16 UTC, kobihk commented on .gitignore
> +reload.ps1
Please make sure you have a new line in the end of the file

2023-01-19 23:16 UTC, kobihk commented on .gitignore
> +reload.ps1
אם הסקריפט הזה משמש רק אותך, עדיף להוסיף את הקובץ/תיקיה באופן מקומי ב: .git/info/exclude
בדרך כלל, נוסיף ל-gitignore רק שמות קבצים שיכולים להיות רלוונטיים לכולם, לא עבור סקריפטים פרטיים
```suggestion
# Running script
reload.ps1
```
```suggestion
# Running script
reload.ps1
```

2023-01-21 19:34 UTC, NicolePauzner approved these changes

2023-01-21 19:34 UTC, ofirtzabari approved these changes

2023-01-21 19:34 UTC, kobihk approved these changes

2023-01-21 19:36 UTC, merged